apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-canary
  template:
    metadata:
      labels:
        app: nginx-canary
    spec:
      containers:
        - name: nginx
          image: nginx-image:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 80